[build]
target = "aarch64-apple-darwin"

[target.aarch64-unknown-linux-gnu]

[target.wasm32-unknown-unknown]

[env]
CFLAGS = "-fno-asynchronous-unwind-tables"
CXXFLAGS = "-fno-asynchronous-unwind-tables"
